### ISSUE TITLE
Update ImGui version?

### ISSUE THREAD

**Issue by sairus7** [JuliaImGui/ImPlot.jl#17]
What should be done do add a newer ImGui version as a dependency?
Should we wait for CImGui.jl 1.82.0 release, or move to LibCImGui 1.82.2 only?

**Comment by wsphillips** [comment]
Edit: Sorry I realized you were asking about updating to CImGui.jl v1.82 and not CImPlot.jl. I don't plan to upgrade until it gets tagged officially.

**Comment by sefffal** [comment]
I started some work on adapting to the new imgui-pack packages on a fork: https://github.com/sefffal/ImPlot.jl
For now I’m just fixing API breakage as I go, having adapted heatmaps, lines, scatter, and colour scales.
This way it’s working with multi viewport and docking.
Maybe that can be a useful stopgap for you until CImGui and ImPlot are officially updated.

**Comment by wsphillips** [comment]
ah, ok. I hope you haven't spent too much time writing out things by hand! 

I really need to sit down and do this update to the generator :weary:

**Comment by sefffal** [comment]
It's not bad at all, cimgui-pack now also generates bindings for implot inside LibCImGui.
I just swapped to that, and added some loops with eval to hook everything up. For example: https://github.com/sefffal/ImPlot.jl/blob/a8f3f4197e897915431f7febf294c5dba6174a3b/src/lines.jl#L96

**Comment by sairus7** [comment]
Unfortunately, I could not install and use your fork, since there are some deps that cannot be resolved or instantiated from Manifest.toml

**Comment by wsphillips** [comment]
@sefffal @sairus7 @Gnimuc development happening on the `gen-update` branch. Just a few more method extensions to go before we can try integrating the new generated code. See:

https://github.com/wsphillips/ImPlot.jl/blob/gen_update/gen/generator.jl

and preview of the WIP output (ignore the leftover prologue/epilogue for now)

https://github.com/wsphillips/ImPlot.jl/blob/gen_update/gen/tmp/libcimplot.jl

When finished we should be able to more easily update to any version with some GitHub action magic

**Comment by wsphillips** [comment]
@sefffal @sairus7 @Gnimuc The generator script is mostly done and I've roughly incorporated it into the rest of the library. There are some lingering edge cases and a few places could use some cleaned up syntax. But otherwise it's just a matter of running through the `implot_demo.jl` and checking all the bindings are behaving normally.

At this point the library almost writes itself :sweat_smile: and most of the issues are with method ambiguities that need resolving in the convenience functions. A lot can be tossed out now... In any case, this sets the stage for not only upgrading to newer versions of implot, but also being mega lazy and triggering automatic builds after upstream tags.

@Gnimuc I wasn't able to get variadic function wrapping to work, even though it was enabled. Does it have to be used in conjunction with the `@ccall` wrapping style? I've stuck to regular `ccall` because it's easiest to destructure during parsing. 

P.S. If anyone wants to lend a hand weeding out the last bugs, I would welcome the help!

**Comment by Gnimuc** [comment]
> @Gnimuc I wasn't able to get variadic function wrapping to work, even though it was enabled. Does it have to be used in conjunction with the @ccall wrapping style?

Yes. `ccall`'s support for variadic functions is very limited, so Clang.jl currently only supports `@ccall`.
